{{- if and .Values.profiles.create (not .Values.profiles.existingConfigMap) (not .Values.profiles.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runeward.profilesSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runeward.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $content := .Values.profiles.data }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
